/* SPDX-License-Identifier: GPL-2.0 */
/*
 * mtk-dsp-common.h  --  Mediatek dsp common function
 *
 * Copyright (c) 2018 MediaTek Inc.
 * Author: ChiPeng Chang <chipeng.chang@mediatek.com>
 */

#ifndef AUDIO_DSP_COMMON_DEFINE_H
#define AUDIO_DSP_COMMON_DEFINE_H

#include <audio_playback_msg_id.h>

/* task command param1 */
enum {
	AUDIO_DSP_TASK_PCM_HWPARAM_DL = 0x1,
	AUDIO_DSP_TASK_PCM_HWPARAM_UL = 0x2,
	AUDIO_DSP_TASK_PCM_HWPARAM_REF = 0x4,
};

enum {
	AUDIO_TASK_VOIP_ID = 0,
	AUDIO_TASK_PRIMARY_ID,
	AUDIO_TASK_OFFLOAD_ID,
	AUDIO_TASK_DEEPBUFFER_ID,
	AUDIO_TASK_PLAYBACK_ID,
	AUDIO_TASK_MUSIC_ID,
	AUDIO_TASK_CAPTURE_RAW_ID,
	AUDIO_TASK_CAPTURE_UL1_ID,
	AUDIO_TASK_A2DP_ID,
	AUDIO_TASK_BLEDL_ID,
	AUDIO_TASK_BLEUL_ID,
	AUDIO_TASK_BTDL_ID,
	AUDIO_TASK_BTUL_ID,
	AUDIO_TASK_DATAPROVIDER_ID,
	AUDIO_TASK_CALL_FINAL_ID,
	AUDIO_TASK_FAST_ID,
	AUDIO_TASK_KTV_ID,
	AUDIO_TASK_FM_ADSP_ID,
	AUDIO_TASK_UL_PROCESS_ID,
	AUDIO_TASK_ECHO_REF_ID,
	AUDIO_TASK_ECHO_REF_DL_ID,
	AUDIO_TASK_USBDL_ID,
	AUDIO_TASK_USBUL_ID,
	AUDIO_TASK_MDDL_ID,
	AUDIO_TASK_MDUL_ID,
	AUDIO_TASK_SPATIALIZER_ID,
	AUDIO_TASK_DYNAMIC_ID,
	AUDIO_TASK_CALLDL_ID,
	AUDIO_TASK_CALLUL_ID,
#if IS_ENABLED(CONFIG_MTK_ADSP_AUTO_HFP_CLIENT_SUPPORT)
	AUDIO_TASK_HFP_CLIENT_RX_ADSP_ID,
#endif
#if IS_ENABLED(CONFIG_MTK_ADSP_AUTO_ANC_SUPPORT)
	AUDIO_TASK_ANC_ADSP_ID,
#endif
#if IS_ENABLED(CONFIG_MTK_ADSP_AUTO_EXTSTREAM_SUPPORT)
	AUDIO_TASK_EXTSTREAM1_ADSP_ID,
	AUDIO_TASK_EXTSTREAM2_ADSP_ID,
#endif
#if IS_ENABLED(CONFIG_SND_SOC_MTK_AUTO_AUDIO_DSP)
#if IS_ENABLED(CONFIG_MTK_ADSP_AUTO_MULTI_PLAYBACK_SUPPORT)
	AUDIO_TASK_SUB_PLAYBACK_ID,
#endif
	AUDIO_TASK_PLAYBACK0_ID,
	AUDIO_TASK_PLAYBACK1_ID,
	AUDIO_TASK_PLAYBACK2_ID,
	AUDIO_TASK_PLAYBACK3_ID,
	AUDIO_TASK_PLAYBACK4_ID,
	AUDIO_TASK_PLAYBACK5_ID,
	AUDIO_TASK_PLAYBACK6_ID,
	AUDIO_TASK_PLAYBACK7_ID,
	AUDIO_TASK_PLAYBACK8_ID,
	AUDIO_TASK_PLAYBACK9_ID,
	AUDIO_TASK_PLAYBACK10_ID,
	AUDIO_TASK_PLAYBACK11_ID,
	AUDIO_TASK_PLAYBACK12_ID,
	AUDIO_TASK_PLAYBACK13_ID,
	AUDIO_TASK_PLAYBACK14_ID,
	AUDIO_TASK_PLAYBACK15_ID,
	AUDIO_TASK_CAPTURE_MCH_ID,
#if IS_ENABLED(CONFIG_MTK_ADSP_AUTO_HFP_CLIENT_SUPPORT)
	AUDIO_TASK_HFP_CLIENT_TX_ADSP_ID,
#endif
#endif
	AUDIO_TASK_DAI_NUM,
};

enum {
	AUDIO_DSP_AFE_SHARE_MEM_ID = 0,
	AUDIO_DSP_SHARE_MEM_NUM,
};

enum {
	MEMORY_AUDIO_SRAM,
	MEMORY_AUDIO_DRAM,
	MEMORY_SYSTEM_TCM,
};

enum{
	BUFFER_TYPE_SHARE_MEM,
	BUFFER_TYPE_HW_MEM
};

enum {
	ADSP_TASK_ATTR_DEFAULT,
	ADSP_TASK_ATTR_MEMDL,
	ADSP_TASK_ATTR_MEMUL,
	ADSP_TASK_ATTR_MEMREF,
	ADSP_TASK_ATTR_RUNTIME,
	ADSP_TASK_ATTR_FEATUREID,
	ADSP_TASK_ATTR_PROPERTY,
	ADSP_TASK_ATTR_REF_RUNTIME,
	ADSP_TASK_ATTR_LATENCY_RATE,
	ADSP_TASK_ATTR_LATENCY_FRAME,
	ADSP_TASK_ATTR_LATENCY_IRQNUM,
	ADSP_TASK_ATTR_ADSP_LATENCY_SUPPORT,
	ADSP_TASK_ATTR_KERNEL_LATENCY_SUPPORT,
	ADSP_TASK_ATTR_ADSP_SLC_SIGN,
	ADSP_TASK_ATTR_ADSP_SLC_DMASIZE,
	ADSP_TASK_ATTR_ADSP_SLC_BW,
	ADSP_TASK_ATTR_NUM
};

/* dl consume param2 status */
enum {
	ADSP_DL_CONSUME_OK,
	ADSP_DL_CONSUME_RESET,
	ADSP_DL_CONSUME_UNDERFLOW,
	ADSP_UL_READ_RESET,
};

#endif
