subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
obj-m += wl2868c.o
obj-m += fan53870.o
obj-m += DIO8018.o
obj-m += pmic_ldo_set_common.o