
# Copyright (C) 2016 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.




ifeq ($(findstring _aging,$(PROJECT_DTB_NAMES)),_aging)
subdir-ccflags-y += -DAGING_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_6360_alpha_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_6360_alpha_4gb_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/K6853v1_64_6360_alpha_120hz_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_6360_alpha_120hz_turbomcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_turbo_2280x1080_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_2280x1080_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853tv1_64_mcl_k419)
subdir-ccflags-y += -DMT6853T
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853tv1_64_120hz_mcl_k419)
subdir-ccflags-y += -DMT6853T
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_rf6190_4gb_1866_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_rf6190_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_6360_alpha_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853v1_64_6360_alpha_90hz_4gb_mcl_k419)
subdir-ccflags-y += -DMT6853
subdir-ccflags-y += -DMC50_LOAD
endif

ifeq ($(PROJECT_DTB_NAMES),mediatek/k6853tv1_64_mcl_k419)
subdir-ccflags-y += -DMT6853T
subdir-ccflags-y += -DMC50_LOAD
endif
