ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/memory/mediatek/

obj-$(CONFIG_MTK_EMI_LEGACY) += emicen.o
obj-$(CONFIG_MTK_EMI_LEGACY) += emimpu.o
obj-$(CONFIG_MTK_EMI_LEGACY) += emiisu.o
obj-$(CONFIG_MTK_EMI_LEGACY) += emictrl.o
