ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/alsps/inc
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/hwmon/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/sensorHub/inc_v1
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/scp

obj-$(CONFIG_MTK_SENSOR_SUPPORT)	:=  alspshub.o

