# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(srctree)/drivers/misc/mediatek/i3c_i2c_wrap \
             -I$(DEVICE_MODULES_PATH)/drivers/i3c/master

obj-$(CONFIG_MTK_I3C_I2C_WRAP) += mtk-i3c-i2c-wrap.o
