# SPDX-License-Identifier: GPL-2.0

#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \
imgsensor_isp6s_mon-objs += camera_hw/gpio/gpio.o \
#obj-y           += imgsensor_oc.o
