# SPDX-License-Identifier: GPL-2.0

#
# Makefile for misc devices that really don't fit anywhere else.
#
# ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

# obj-y		+= ../../common/v1_1/camera_hw/regulator/
# obj-y		+= ../../common/v1_1/camera_hw/gpio/
# obj-y		+= ../../common/v1_1/camera_hw/mclk/
# obj-y		+= imgsensor_cfg_table.o
# obj-y           += imgsensor_pwr_seq.o
#obj-y           += imgsensor_oc.o

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

# imgsensor_isp6s_lag-objs += \
# 	../common/v1_1/camera_hw/regulator/regulator.o \
# 	../common/v1_1/camera_hw/gpio/gpio.o \
# 	../common/v1_1/camera_hw/mclk/mclk.o \

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s_lag-objs += \
	../common/v1_1/camera_hw/regulator/regulator.o \
	../common/v1_1/camera_hw/gpio/gpio.o \
	../common/v1_1/camera_hw/mclk/mclk.o \

imgsensor_isp6s_lag-objs += \
	camera_hw/imgsensor_cfg_table.o \
	camera_hw/imgsensor_pwr_seq.o \
