## subdir-ccflags-y += IS(srctree)/arch/arm64/kvm/hyp/include/
hyp-obj-y := pkvm_mkp_hyp.o policy.o sharebuf.o handle.o mapping.o action.o emi_mpu_v2.o mkp_handler.o lib/malloc.o lib/list_debug.o
include $(srctree)/arch/arm64/kvm/hyp/nvhe/Makefile.module
