/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2024 MediaTek Inc.
 */

// Here saves all MTK's smc call related to pKVM

// It is for el1 only
#define SMC_ID_MTK_PKVM_ADD_HVC 0xC400ff10
#define SMC_ID_MTK_PKVM_TMEM_REGION_PROTECT		0xBB00FFA7
#define SMC_ID_MTK_PKVM_TMEM_REGION_UNPROTECT	0xBB00FFA8
#define SMC_ID_MTK_PKVM_TMEM_PAGE_PROTECT		0xBB00FFA9
#define SMC_ID_MTK_PKVM_TMEM_PAGE_UNPROTECT		0xBB00FFAA
#define SMC_ID_MTK_PKVM_SMMU_SEC_MAP            0xBB00FFAB
#define SMC_ID_MTK_PKVM_SMMU_SEC_UNMAP          0xBB00FFAC
#define SMC_ID_MTK_PKVM_SMMU_MEM_SHARE          0xBB00FFAD
#define SMC_ID_MTK_PKVM_SMMU_DEBUG_DUMP         0xBB00FFAE
#define SMC_ID_MTK_PKVM_SMMU_SEC_REGION_MAP     0xBB00FFAF
#define SMC_ID_MTK_PKVM_SMMU_SEC_REGION_UNMAP   0xBB00FFB0
#define SMC_ID_MTK_PKVM_SMMU_PAGE_TABLE_MERGE   0xBB00FFB1

// smc result code
#define SMC_RET_MTK_PKVM_SMC_HANDLER_DUPLICATED_ID -1
