ifneq (, $(filter $(strip $(CONFIG_MTK_PLAT_POWER_6893)),m y))
    obj-y += v1/
else ifneq (, $(filter $(strip $(CONFIG_MTK_TINYSYS_MCUPM_SUPPORT)),m y))
    obj-$(CONFIG_MTK_TINYSYS_MCUPM_SUPPORT) += v2/
endif