// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#include <linux/io.h>

#include <mt6991_dcm_internal.h>
#include <mt6991_dcm_autogen.h>
#include <mtk_dcm.h>
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_l3c_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_L3_SHARE_DCM_CTRL) &
		MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_l3c_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_L3_SHARE_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_L3_SHARE_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_L3_SHARE_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_L3_SHARE_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK ((0x10001U << 0))
#define MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_ON ((0x10001U << 0))
#define MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_acp_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP_ADB_DCM_CFG0) &
		MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_acp_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP_ADB_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP_ADB_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP_ADB_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP_ADB_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK ((0x1fff07ffU << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON ((0x1fff07ffU << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_adb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_ADB_FIFO_DCM_EN) &
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_adb_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_ADB_FIFO_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_ADB_FIFO_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_ADB_FIFO_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_ADB_FIFO_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK ((0xffU << 0))
#define MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_ON ((0xffU << 0))
#define MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_stalldcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_stalldcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK ((0x1ffffU << 8))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON ((0x1ffffU << 8))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_apb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_apb_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK ((0x1001U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_ON ((0x1001U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_io_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_L3GIC_ARCH_CG_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_io_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_L3GIC_ARCH_CG_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_L3GIC_ARCH_CG_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_L3GIC_ARCH_CG_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_L3GIC_ARCH_CG_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK ((0x111U << 16))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_ON ((0x111U << 16))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_ON ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_bus_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG1) &
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_bus_qdcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG1,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG1) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG1,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG1) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK ((0x11111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON ((0x11111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_core_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG2) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG3) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_core_qdcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG2,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG2) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG3,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG3) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG2,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG2) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG3,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_QDCM_CONFIG3) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK ((0xffff0003U << 0))
#define MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON ((0x45040001U << 1))
#define MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_OFF ((0x1141U << 19))

bool A0_dcm_mcusys_par_wrap_mcu_bkr_ldcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL) &
		MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON);

	return ret;
}

void A0_dcm_mcusys_par_wrap_mcu_bkr_ldcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_OFF);
	}
}

#define B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK ((0xffff0003U << 0))
#define B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON ((0x8A080003U << 0))
#define B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_OFF ((0x1141U << 19))

bool B0_dcm_mcusys_par_wrap_mcu_bkr_ldcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL) &
		B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) ==
		B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON);

	return ret;
}

void B0_dcm_mcusys_par_wrap_mcu_bkr_ldcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL) &
			~B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) |
			B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CI700_DCM_CTRL) &
			~B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) |
			B0_MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK ((0x7U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_ON ((0x7U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_OFF ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_OFF ((0x1U << 0))

bool dcm_mcusys_par_wrap_mcu_cbip_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_3TO1_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO1_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_4TO2_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO5_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_P2P_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_L3GIC_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_INFRA_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_cbip_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_3TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_3TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_4TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_4TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO5_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO5_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_P2P_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_P2P_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_L3GIC_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_L3GIC_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_ON);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_INFRA_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_INFRA_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_3TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_3TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_4TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_4TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO5_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_2TO5_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_P2P_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_P2P_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_L3GIC_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_L3GIC_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG6_OFF);
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_INFRA_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_CBIP_CABGEN_1TO2_INFRA_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG7_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_misc_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG) &
		MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_misc_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG) &
			~MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG) &
			~MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_dsu_acp_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN) &
		MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_dsu_acp_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK ((0xfU << 1))
#define MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_OFF ((0xfU << 1))

bool dcm_mcusys_par_wrap_mcu_chi_mon_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN) &
		MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_chi_mon_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_gic_spi_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_GIC_SPI_SLOW_CK_CFG) &
		MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_gic_spi_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_GIC_SPI_SLOW_CK_CFG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_GIC_SPI_SLOW_CK_CFG) &
			~MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_GIC_SPI_SLOW_CK_CFG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_GIC_SPI_SLOW_CK_CFG) &
			~MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK ((0x1U << 2))
#define MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_OFF ((0x1U << 2))

bool dcm_mcusys_par_wrap_mcu_ebg_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_NON_SEC_EBG_CKE_WRAP_FIFO_CFG) &
		MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_ebg_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_EBG_CKE_WRAP_FIFO_CFG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_EBG_CKE_WRAP_FIFO_CFG) &
			~MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_NON_SEC_EBG_CKE_WRAP_FIFO_CFG,
			(reg_read(MCUSYS_PAR_WRAP_NON_SEC_EBG_CKE_WRAP_FIFO_CFG) &
			~MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_OFF);
	}
}

#define BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_io_ctrl_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_io_ctrl_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0,
			(reg_read(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
	} else {
		reg_write(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0,
			(reg_read(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_IO_CTRL_AO_INFRA_BUS_DCM_REG0_OFF);
	}
}

#define BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_MASK ((0x1U << 4))
#define BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_ON ((0x1U << 4))
#define BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_io_noc_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0) &
		BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_io_noc_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0,
			(reg_read(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_ON);
	} else {
		reg_write(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0,
			(reg_read(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_IO_NOC_AO_INFRA_BUS_DCM_REG0_OFF);
	}
}

#define BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK ((0x1U << 4))
#define BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_ON ((0x1U << 4))
#define BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_mem_intf_noc_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0) &
		BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_mem_intf_noc_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_ON);
	} else {
		reg_write(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_OFF);
	}
}

#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK ((0x7U << 2))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK ((0x9U << 4))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK ((0x1U << 21))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK ((0x1U << 22))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK ((0x1U << 20))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK ((0x1U << 24))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_MASK ((0x1U << 23))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_ON ((0x7U << 2))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_ON ((0x9U << 4))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_ON ((0x1U << 21))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_ON ((0x1U << 22))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_ON ((0x1U << 20))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_ON ((0x1U << 24))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_ON ((0x1U << 23))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_mem_ctrl_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_5) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_ON);

	return ret;
}

void dcm_bcrm_apinfra_mem_ctrl_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_5,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_5) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_ON);
	} else {
		reg_write(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_5,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_5) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG6_OFF);
	}
}

#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK ((0xa49U << 5))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON ((0xa49U << 5))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG3_OFF ((0x0U << 0))

bool A0_dcm_peri_ao_bcrm_peri_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
	ret &= ((reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
	ret &= ((reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
	ret &= ((reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON);

	return ret;
}

void A0_dcm_peri_ao_bcrm_peri_bus_dcm(int on)
{
	if (on) {
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON);
	} else {
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF);
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF);
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF);
		reg_write(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3,
			(reg_read(A0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG3_OFF);
	}
}

bool B0_dcm_peri_ao_bcrm_peri_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
	ret &= ((reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
	ret &= ((reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
	ret &= ((reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON);

	return ret;
}

void B0_dcm_peri_ao_bcrm_peri_bus_dcm(int on)
{
	if (on) {
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON);
	} else {
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF);
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF);
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF);
		reg_write(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3,
			(reg_read(B0_VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG3_OFF);
	}
}

#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK ((0x3e013U << 1))
#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON ((0x13U << 1))
#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_OFF ((0x3U << 1))

bool dcm_vlp_ao_bcrm_vlp_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0) &
		VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) ==
		VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_vlp_ao_bcrm_vlp_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0,
			(reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0) &
			~VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) |
			VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON);
	} else {
		reg_write(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0,
			(reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0) &
			~VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) |
			VLP_AO_BCRM_VLP_BUS_DCM_REG0_OFF);
	}
}

