#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/tof/core/inc
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/tof/core/src
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/tof/core/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/

#obj-$(CONFIG_MTK_V4L2_LENS) += vl53l4.o
