ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
obj-m += botai_touch_two.o
botai_touch_two-y	+=  gt9xx_driver.o
botai_touch_two-y	+=  tpd_control.o
botai_touch_two-y	+=  tpd_button.o
