// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2023 MediaTek Inc.
 * Author: Wendy-ST Lin <wendy-st.lin@mediatek.com>
 */
#include <dt-bindings/interconnect/mtk,mmqos.h>
#include <dt-bindings/interconnect/mtk,emi.h>
#include <dt-bindings/memory/mt6991-larb-port.h>
#include <linux/module.h>
#include <linux/of_platform.h>
#include "mmqos-mtk.h"
static const struct mtk_node_desc node_descs_mt6991[] = {
	DEFINE_MNODE(common0,
		SLAVE_COMMON(0), 0, false, 0x0, MMQOS_NO_LINK), //DISP
	DEFINE_MNODE(mdp_common0,
		SLAVE_COMMON(1), 0, false, 0x0, MMQOS_NO_LINK), //MDP
	DEFINE_MNODE(common0_port0,
		MASTER_COMMON_PORT(0, 0), 0, false, 0x1, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port1,
		MASTER_COMMON_PORT(0, 1), 0, false, 0x2, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port2,
		MASTER_COMMON_PORT(0, 2), 0, false, 0x2, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port3,
		MASTER_COMMON_PORT(0, 3), 0, false, 0x1, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port4,
		MASTER_COMMON_PORT(0, 4), 0, false, 0x2, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port5,
		MASTER_COMMON_PORT(0, 5), 0, false, 0x1, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port6,
		MASTER_COMMON_PORT(0, 6), 0, false, 0x1, SLAVE_COMMON(0)),
	DEFINE_MNODE(common0_port7,
		MASTER_COMMON_PORT(0, 7), 0, false, 0x1, SLAVE_COMMON(0)), // larb2 DC
	DEFINE_MNODE(mdp_common0_port0,
		MASTER_COMMON_PORT(1, 0), 0, false, 0x12, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port1,
		MASTER_COMMON_PORT(1, 1), 0, false, 0x11, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port2,
		MASTER_COMMON_PORT(1, 2), 0, false, 0x12, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port3,
		MASTER_COMMON_PORT(1, 3), 0, false, 0x11, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port4,
		MASTER_COMMON_PORT(1, 4), 0, false, 0x12, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port5,
		MASTER_COMMON_PORT(1, 5), 0, false, 0x11, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port6,
		MASTER_COMMON_PORT(1, 6), 0, false, 0x12, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port7,
		MASTER_COMMON_PORT(1, 7), 0, false, 0x11, SLAVE_COMMON(1)),
	DEFINE_MNODE(mdp_common0_port8,
		MASTER_COMMON_PORT(1, 8), 0, false, 0x11, SLAVE_COMMON(1)),
	/* SMI DISP COMMON */
	DEFINE_MNODE(DISP_larb0,  SLAVE_LARB(0),  0,   false, 0x0, MASTER_COMMON_PORT(0, 0)),
	DEFINE_MNODE(DISP_larb37, SLAVE_LARB(37), 0,   false, 0x0, MASTER_COMMON_PORT(0, 0)),
	DEFINE_MNODE(MDP_larb2,   SLAVE_LARB(2),  0,   false, 0x0, MASTER_COMMON_PORT(0, 7)), //mdp dc
	DEFINE_MNODE(MDP_larb49,  SLAVE_LARB(49), 0,   false, 0x0, MASTER_COMMON_PORT(0, 0)), //mdp rrot dl
	DEFINE_MNODE(DISP_larb32, SLAVE_LARB(32), 0,   false, 0x0, MASTER_COMMON_PORT(0, 1)),
	DEFINE_MNODE(DISP_larb1,  SLAVE_LARB(1),  0,   false, 0x0, MASTER_COMMON_PORT(0, 1)),
	DEFINE_MNODE(DISP_larb36, SLAVE_LARB(36), 0,   false, 0x0, MASTER_COMMON_PORT(0, 1)),
	DEFINE_MNODE(VDEC_larb5,  SLAVE_LARB(5),  0,   false, 0x0, MASTER_COMMON_PORT(0, 2)),
	DEFINE_MNODE(VENC_larb41, SLAVE_LARB(41), 0,   false, 0x0, MASTER_COMMON_PORT(0, 3)),
	DEFINE_MNODE(VENC_larb7,  SLAVE_LARB(7),  0,   false, 0x0, MASTER_COMMON_PORT(0, 3)),
	DEFINE_MNODE(IMG_larb11,  SLAVE_LARB(11), 0,   false, 0x0, MASTER_COMMON_PORT(0, 4)),
	DEFINE_MNODE(IMG_larb28,  SLAVE_LARB(28), 0,   false, 0x0, MASTER_COMMON_PORT(0, 4)),
	DEFINE_MNODE(IMG_larb10,  SLAVE_LARB(10), 0,   false, 0x0, MASTER_COMMON_PORT(0, 4)),
	DEFINE_MNODE(IMG_larb38,  SLAVE_LARB(38), 0,   false, 0x0, MASTER_COMMON_PORT(0, 4)),
	DEFINE_MNODE(IMG_larb12,  SLAVE_LARB(12), 0,   false, 0x0, MASTER_COMMON_PORT(0, 4)),
	DEFINE_MNODE(IMG_larb40,  SLAVE_LARB(40), 0,   false, 0x0, MASTER_COMMON_PORT(0, 4)),
	DEFINE_MNODE(CAM_larb16,  SLAVE_LARB(16), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb44,  SLAVE_LARB(44), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb45,  SLAVE_LARB(45), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb25,  SLAVE_LARB(25), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb19,  SLAVE_LARB(19), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb13,  SLAVE_LARB(13), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb14,  SLAVE_LARB(14), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	DEFINE_MNODE(CAM_larb29,  SLAVE_LARB(29), 0,   false, 0x0, MASTER_COMMON_PORT(0, 5)),
	/* SMI MDP COMMON */
	DEFINE_MNODE(DISP_larb33, SLAVE_LARB(33), 0,   false, 0x0, MASTER_COMMON_PORT(1, 0)),
	DEFINE_MNODE(DISP_larb20, SLAVE_LARB(20), 0,   false, 0x0, MASTER_COMMON_PORT(1, 0)),
	DEFINE_MNODE(DISP_larb35, SLAVE_LARB(35), 0,   false, 0x0, MASTER_COMMON_PORT(1, 0)),
	DEFINE_MNODE(DISP_larb21, SLAVE_LARB(21), 0,   false, 0x0, MASTER_COMMON_PORT(1, 1)),
	DEFINE_MNODE(MML_larb3,  SLAVE_LARB(3),  0,   false, 0x0, MASTER_COMMON_PORT(1, 8)), //mml dc
	DEFINE_MNODE(DISP_larb34, SLAVE_LARB(34), 0,   false, 0x0, MASTER_COMMON_PORT(1, 1)),
	DEFINE_MNODE(MML_larb48,  SLAVE_LARB(48), 0,   false, 0x0, MASTER_COMMON_PORT(1, 1)), //mml ir dl
	DEFINE_MNODE(VDEC_larb4,  SLAVE_LARB(4),  0,   false, 0x0, MASTER_COMMON_PORT(1, 2)),
	DEFINE_MNODE(VDEC_larb6,  SLAVE_LARB(6),  0,   false, 0x0, MASTER_COMMON_PORT(1, 3)),
	DEFINE_MNODE(VENC_larb8,  SLAVE_LARB(8),  0,   false, 0x0, MASTER_COMMON_PORT(1, 4)),
	DEFINE_MNODE(VENC_larb42, SLAVE_LARB(42), 0,   false, 0x0, MASTER_COMMON_PORT(1, 4)),
	DEFINE_MNODE(VENC_larb24, SLAVE_LARB(24), 0,   false, 0x0, MASTER_COMMON_PORT(1, 4)),
	DEFINE_MNODE(VENC_larb47, SLAVE_LARB(47), 0,   false, 0x0, MASTER_COMMON_PORT(1, 4)),
	DEFINE_MNODE(IMG_larb22,  SLAVE_LARB(22), 0,   false, 0x0, MASTER_COMMON_PORT(1, 5)),
	DEFINE_MNODE(IMG_larb18,  SLAVE_LARB(18), 0,   false, 0x0, MASTER_COMMON_PORT(1, 5)),
	DEFINE_MNODE(IMG_larb39,  SLAVE_LARB(39), 0,   false, 0x0, MASTER_COMMON_PORT(1, 5)),
	DEFINE_MNODE(IMG_larb23,  SLAVE_LARB(23), 0,   false, 0x0, MASTER_COMMON_PORT(1, 5)),
	DEFINE_MNODE(IMG_larb9,   SLAVE_LARB(9),  0,   false, 0x0, MASTER_COMMON_PORT(1, 5)),
	DEFINE_MNODE(IMG_larb15,  SLAVE_LARB(15), 0,   false, 0x0, MASTER_COMMON_PORT(1, 5)),
	DEFINE_MNODE(CAM_larb13,  SLAVE_LARB(13), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb43,  SLAVE_LARB(43), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb17,  SLAVE_LARB(17), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb46,  SLAVE_LARB(46), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb26,  SLAVE_LARB(26), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb27,  SLAVE_LARB(27), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb29,  SLAVE_LARB(29), 0,   false, 0x0, MASTER_COMMON_PORT(1, 6)),
	DEFINE_MNODE(CAM_larb14,  SLAVE_LARB(14), 0,   false, 0x0, MASTER_COMMON_PORT(1, 7)),
	DEFINE_MNODE(CAM_larb30,  SLAVE_LARB(30), 0,   false, 0x0, MASTER_COMMON_PORT(1, 7)), //CCU
	/* LARB0 */
	DEFINE_MNODE(ovl_rdma2_hdr_larb0_0,
		MASTER_LARB_PORT(SMMU_L0_P0_OVL_RDMA2_HDR),                7, false, 0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma7_hdr_larb0_1,
		MASTER_LARB_PORT(SMMU_L0_P1_OVL_RDMA7_HDR),                7, false, 0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma2_larb0_2,
		MASTER_LARB_PORT(SMMU_L0_P2_OVL_RDMA2),                    8, false, 0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma7_larb0_3,
		MASTER_LARB_PORT(SMMU_L0_P3_OVL_RDMA7),                    8, false, 0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma2_hdr_stash_larb0_6,
		MASTER_LARB_PORT(SMMU_L0_P6_OVL_RDMA2_HDR_STASH),          5, true,  0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma7_hdr_stash_larb0_7,
		MASTER_LARB_PORT(SMMU_L0_P7_OVL_RDMA7_HDR_STASH),          5, true,  0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma2_stash_larb0_8,
		MASTER_LARB_PORT(SMMU_L0_P8_OVL_RDMA2_STASH),              5, true,  0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(ovl_rdma7_stash_larb0_9,
		MASTER_LARB_PORT(SMMU_L0_P9_OVL_RDMA7_STASH),              5, true,  0x0, SLAVE_LARB(0)),
	DEFINE_MNODE(disp_fake0_larb0_12,
		MASTER_LARB_PORT(SMMU_L0_P12_DISP_FAKE0),                  8, false, 0x0, SLAVE_LARB(0)),
	/* LARB1 */
	DEFINE_MNODE(ovl_rdma3_hdr_larb1_0,
		MASTER_LARB_PORT(SMMU_L1_P0_OVL_RDMA3_HDR),                7, false, 0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma6_hdr_larb1_1,
		MASTER_LARB_PORT(SMMU_L1_P1_OVL_RDMA6_HDR),                7, false, 0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma3_larb1_2,
		MASTER_LARB_PORT(SMMU_L1_P2_OVL_RDMA3),                    8, false, 0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma6_larb1_3,
		MASTER_LARB_PORT(SMMU_L1_P3_OVL_RDMA6),                    8, false, 0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(mdp_rdma1_larb1_4,
		MASTER_LARB_PORT(SMMU_L1_P4_MDP_RDMA1),                    8, false, 0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(disp_wdma1_larb1_6,
		MASTER_LARB_PORT(SMMU_L1_P6_DISP_WDMA1),                   9, true,  0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma3_hdr_stash_larb1_7,
		MASTER_LARB_PORT(SMMU_L1_P7_OVL_RDMA3_HDR_STASH),          5, true,  0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma6_hdr_stash_larb1_8,
		MASTER_LARB_PORT(SMMU_L1_P8_OVL_RDMA6_HDR_STASH),          5, true,  0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma3_stash_larb1_9,
		MASTER_LARB_PORT(SMMU_L1_P9_OVL_RDMA3_STASH),              5, true,  0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(ovl_rdma6_stash_larb1_10,
		MASTER_LARB_PORT(SMMU_L1_P10_OVL_RDMA6_STASH),             5, true,  0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(mdp_rdma1_stash_larb1_11,
		MASTER_LARB_PORT(SMMU_L1_P11_MDP_RDMA1_STASH),             5, true,  0x0, SLAVE_LARB(1)),
	DEFINE_MNODE(disp_fake1_larb1_15,
		MASTER_LARB_PORT(SMMU_L1_P15_DISP_FAKE1),                  8, false, 0x0, SLAVE_LARB(1)),
	/* LARB2 */
	DEFINE_MNODE(mdp_rdma2_larb2_0,
		MASTER_LARB_PORT(SMMU_L2_P0_MDP_RDMA2),                    8, false, 0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_wrot2_larb2_1,
		MASTER_LARB_PORT(SMMU_L2_P1_MDP_WROT2),                    7, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rdma1_larb2_2,
		MASTER_LARB_PORT(SMMU_L2_P2_MDP_RDMA1),                    8, false, 0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_wrot1_larb2_3,
		MASTER_LARB_PORT(SMMU_L2_P3_MDP_WROT1),                    7, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rdma0_larb2_4,
		MASTER_LARB_PORT(SMMU_L2_P4_MDP_RDMA0),                    8, false, 0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_wrot0_larb2_5,
		MASTER_LARB_PORT(SMMU_L2_P5_MDP_WROT0),                    7, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rrot0_larb2_6,
		MASTER_LARB_PORT(SMMU_L2_P6_MDP_RROT0),                    6, false, 0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_fg0_larb2_7,
		MASTER_LARB_PORT(SMMU_L2_P7_MDP_FG0),                      7, false, 0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_wrot2_stash_larb2_9,
		MASTER_LARB_PORT(SMMU_L2_P9_MDP_WROT2_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rdma1_stash_larb2_10,
		MASTER_LARB_PORT(SMMU_L2_P10_MDP_RDMA1_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_wrot1_stash_larb2_11,
		MASTER_LARB_PORT(SMMU_L2_P11_MDP_WROT1_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rdma0_stash_larb2_12,
		MASTER_LARB_PORT(SMMU_L2_P12_MDP_RDMA0_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_wrot0_stash_larb2_13,
		MASTER_LARB_PORT(SMMU_L2_P13_MDP_WROT0_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rrot0_stash_larb2_14,
		MASTER_LARB_PORT(SMMU_L2_P14_MDP_RROT0_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_rdma2_stash_larb2_15,
		MASTER_LARB_PORT(SMMU_L2_P15_MDP_RDMA2_STASH),		   5, true,  0x0, SLAVE_LARB(2)),
	DEFINE_MNODE(mdp_fake_eng0_larb2_17,
		MASTER_LARB_PORT(SMMU_L2_P17_MDP_FAKE_ENG0),               8, false, 0x0, SLAVE_LARB(2)),
	/* LARB3 */
	DEFINE_MNODE(mdp_rdma2_larb3_0,
		MASTER_LARB_PORT(SMMU_L3_P0_MDP_RDMA2),                    8, false, 0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_wrot2_larb3_1,
		MASTER_LARB_PORT(SMMU_L3_P1_MDP_WROT2),                    7, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rdma1_larb3_2,
		MASTER_LARB_PORT(SMMU_L3_P2_MDP_RDMA1),                    8, false, 0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_wrot1_larb3_3,
		MASTER_LARB_PORT(SMMU_L3_P3_MDP_WROT1),                    7, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rdma0_larb3_4,
		MASTER_LARB_PORT(SMMU_L3_P4_MDP_RDMA0),                    8, false, 0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_wrot0_larb3_5,
		MASTER_LARB_PORT(SMMU_L3_P5_MDP_WROT0),                    7, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rrot0_larb3_6,
		MASTER_LARB_PORT(SMMU_L3_P6_MDP_RROT0),                    6, false, 0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_fg0_larb3_7,
		MASTER_LARB_PORT(SMMU_L3_P7_MDP_FG0),                      7, false, 0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rdma0_stash_larb3_9,
		MASTER_LARB_PORT(SMMU_L3_P9_MDP_RDMA0_STASH),              5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_wrot0_stash_larb3_10,
		MASTER_LARB_PORT(SMMU_L3_P10_MDP_WROT0_STASH),             5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rrot0_stash_larb3_11,
		MASTER_LARB_PORT(SMMU_L3_P11_MDP_RROT0_STASH),             5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rdma2_stash_larb3_12,
		MASTER_LARB_PORT(SMMU_L3_P12_MDP_RDMA2_STASH),             5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_wrot2_stash_larb3_13,
		MASTER_LARB_PORT(SMMU_L3_P13_MDP_WROT2_STASH),             5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_rdma1_stash_larb3_14,
		MASTER_LARB_PORT(SMMU_L3_P14_MDP_RDMA1_STASH),             5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_wrot1_stash_larb3_15,
		MASTER_LARB_PORT(SMMU_L3_P15_MDP_WROT1_STASH),             5, true,  0x0, SLAVE_LARB(3)),
	DEFINE_MNODE(mdp_fake_eng0_larb3_17,
		MASTER_LARB_PORT(SMMU_L3_P17_MDP_FAKE_ENG0),               8, false, 0x0, SLAVE_LARB(3)),
	/* remove LARB4 for Secure VP*/
	/* remove LARB5 for Secure VP*/
	/* remove LARB6 for Secure VP*/
	/* LARB7 */
	DEFINE_MNODE(jpgenc_y_rdma_larb7_7,
		MASTER_LARB_PORT(SMMU_L7_P7_JPGENC_YRD),                   7, false, 0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgenc_c_rdma_larb7_8,
		MASTER_LARB_PORT(SMMU_L7_P8_JPGENC_CRD),                   7, false, 0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgenc_q_table_larb7_9,
		MASTER_LARB_PORT(SMMU_L7_P9_JPGENC_QT),                    7, false, 0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgenc_bsdma_larb7_16,
		MASTER_LARB_PORT(SMMU_L7_P16_JPGENC_BS),                   8, true,  0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgdec_wdma_0_larb7_17,
		MASTER_LARB_PORT(SMMU_L7_P17_JPGDEC_W),                    8, true,  0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgdec_bsdma_0_larb7_18,
		MASTER_LARB_PORT(SMMU_L7_P18_JPGDEC_BS),                   7, false, 0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgdec_wdma_1_larb7_27,
		MASTER_LARB_PORT(SMMU_L7_P27_JPGDEC_W_1),                  8, true,  0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgdec_bsdma_1_larb7_28,
		MASTER_LARB_PORT(SMMU_L7_P28_JPGDEC_BS_1),                 7, false, 0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgdec_huff_offset_1_larb7_29,
		MASTER_LARB_PORT(SMMU_L7_P29_JPGDEC_HUF_1),                8, true,  0x0, SLAVE_LARB(7)),
	DEFINE_MNODE(jpgdec_huff_offset_0_larb7_30,
		MASTER_LARB_PORT(SMMU_L7_P30_JPGDEC_HUF),                  8, true,  0x0, SLAVE_LARB(7)),
	/* LARB8 */
	DEFINE_MNODE(jpgenc_y_rdma_larb8_7,
		MASTER_LARB_PORT(SMMU_L8_P7_JPGENC_YRD),                   7, false, 0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgenc_c_rdma_larb8_8,
		MASTER_LARB_PORT(SMMU_L8_P8_JPGENC_CRD),                   8, true,  0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgenc_q_table_larb8_9,
		MASTER_LARB_PORT(SMMU_L8_P9_JPGENC_QT),                    8, true,  0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgenc_bsdma_larb8_16,
		MASTER_LARB_PORT(SMMU_L8_P16_JPGENC_BS),                   7, false, 0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgdec_wdma_0_larb8_17,
		MASTER_LARB_PORT(SMMU_L8_P17_JPGDEC_W),                    7, false, 0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgdec_bsdma_0_larb8_18,
		MASTER_LARB_PORT(SMMU_L8_P18_JPGDEC_BS),                   8, true,  0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgdec_wdma_1_larb8_27,
		MASTER_LARB_PORT(SMMU_L8_P27_JPGDEC_W_1),                  8, true,  0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgdec_bsdma_1_larb8_28,
		MASTER_LARB_PORT(SMMU_L8_P28_JPGDEC_BS_1),                 7, false, 0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgdec_huff_offset_1_larb8_29,
		MASTER_LARB_PORT(SMMU_L8_P29_JPGDEC_HUF_1),                8, true,  0x0, SLAVE_LARB(8)),
	DEFINE_MNODE(jpgdec_huff_offset_0_larb8_30,
		MASTER_LARB_PORT(SMMU_L8_P30_JPGDEC_HUF),                  8, true,  0x0, SLAVE_LARB(8)),
	/* LARB13 */
	DEFINE_MNODE(camsv_b_cqi_e1_larb13_0,
		MASTER_LARB_PORT(SMMU_L13_P0_CAMSV_B_CQI_E1),              8, false, 0x0, SLAVE_LARB(13)),
	DEFINE_MNODE(camsv_b0_wdma_larb13_1,
		MASTER_LARB_PORT(SMMU_L13_P1_CAMSV_B0_WDMA),               8, true,  0x0, SLAVE_LARB(13)),
	DEFINE_MNODE(camsv_b1_wdma_larb13_2,
		MASTER_LARB_PORT(SMMU_L13_P2_CAMSV_B1_WDMA),               8, true,  0x0, SLAVE_LARB(13)),
	DEFINE_MNODE(camsv_b0_stg_larb13_5,
		MASTER_LARB_PORT(SMMU_L13_P5_CAMSV_B0_STG),                1, true,  0x0, SLAVE_LARB(13)),
	DEFINE_MNODE(camsv_b1_stg_larb13_6,
		MASTER_LARB_PORT(SMMU_L13_P6_CAMSV_B1_STG),                1, true,  0x0, SLAVE_LARB(13)),
	/* LARB14 */
	DEFINE_MNODE(camsv_a_cqi_e1_larb14_0,
		MASTER_LARB_PORT(SMMU_L14_P0_CAMSV_A_CQI_E1),              8, false, 0x0, SLAVE_LARB(14)),
	DEFINE_MNODE(camsv_a0_wdma_larb14_1,
		MASTER_LARB_PORT(SMMU_L14_P1_CAMSV_A0_WDMA),               8, true,  0x0, SLAVE_LARB(14)),
	DEFINE_MNODE(camsv_a1_wdma_larb14_2,
		MASTER_LARB_PORT(SMMU_L14_P2_CAMSV_A1_WDMA),               8, true,  0x0, SLAVE_LARB(14)),
	DEFINE_MNODE(camsv_a0_stg_larb14_4,
		MASTER_LARB_PORT(SMMU_L14_P4_CAMSV_A0_STG),                1, true,  0x0, SLAVE_LARB(14)),
	DEFINE_MNODE(camsv_a1_stg_larb14_5,
		MASTER_LARB_PORT(SMMU_L14_P5_CAMSV_A1_STG),                1, true,  0x0, SLAVE_LARB(14)),
	/* LARB16 */
	DEFINE_MNODE(cqi_r1_larb16_0,
		MASTER_LARB_PORT(SMMU_L16_P0_CQI_R1),                      8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(cqi_r5_larb16_1,
		MASTER_LARB_PORT(SMMU_L16_P1_CQI_R5),                      8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(rawi_r2_larb16_2,
		MASTER_LARB_PORT(SMMU_L16_P2_RAWI_R2),                     8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(rawi_r3_larb16_3,
		MASTER_LARB_PORT(SMMU_L16_P3_RAWI_R3),                     8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(rawi_r4_larb16_4,
		MASTER_LARB_PORT(SMMU_L16_P4_RAWI_R4),                     8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(rawi_r5_larb16_5,
		MASTER_LARB_PORT(SMMU_L16_P5_RAWI_R5),                     8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(bpci_r1_larb16_6,
		MASTER_LARB_PORT(SMMU_L16_P6_BPCI_R1),                     9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(bpci_r3_larb16_7,
		MASTER_LARB_PORT(SMMU_L16_P7_BPCI_R3),                     9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(grmgi_r1_larb16_8,
		MASTER_LARB_PORT(SMMU_L16_P8_GRMGI_R1),                    8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(lsci_r1_larb16_9,
		MASTER_LARB_PORT(SMMU_L16_P9_LSCI_R1),                     8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(imgo_r1_larb16_10,
		MASTER_LARB_PORT(SMMU_L16_P10_IMGO_R1),                    8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(imgo_r2_larb16_11,
		MASTER_LARB_PORT(SMMU_L16_P11_IMGO_R2),                    8, false, 0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(drzb2no_r1_larb16_12,
		MASTER_LARB_PORT(SMMU_L16_P12_DRZB2NO_R1),                 9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(drzb2nbo_r1_larb16_13,
		MASTER_LARB_PORT(SMMU_L16_P13_DRZB2NBO_R1),                9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(gmpo_r1_larb16_14,
		MASTER_LARB_PORT(SMMU_L16_P14_GMPO_R1),                    9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(drzb2nco_r1_larb16_15,
		MASTER_LARB_PORT(SMMU_L16_P15_DRZB2NCO_R1),                9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(awbo_r1_larb16_16,
		MASTER_LARB_PORT(SMMU_L16_P16_AWBO_R1),                    9, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(stg_r1_larb16_17,
		MASTER_LARB_PORT(SMMU_L16_P17_STG_R1),                     5, true,  0x0, SLAVE_LARB(16)),
	DEFINE_MNODE(stg_r2_larb16_18,
		MASTER_LARB_PORT(SMMU_L16_P18_STG_R2),                     5, true,  0x0, SLAVE_LARB(16)),
	/* LARB17 */
	DEFINE_MNODE(yuvo_r1_larb17_0,
		MASTER_LARB_PORT(SMMU_L17_P0_YUVO_R1),                     9, true,  0x0, SLAVE_LARB(17)),
	DEFINE_MNODE(yuvo_r3_larb17_1,
		MASTER_LARB_PORT(SMMU_L17_P1_YUVO_R3),                     9, true,  0x0, SLAVE_LARB(17)),
	DEFINE_MNODE(yuvo_r2_larb17_2,
		MASTER_LARB_PORT(SMMU_L17_P2_YUVO_R2),                     9, true,  0x0, SLAVE_LARB(17)),
	DEFINE_MNODE(drzh2no_r1_larb17_3,
		MASTER_LARB_PORT(SMMU_L17_P3_DRZH2NO_R1),                  9, true,  0x0, SLAVE_LARB(17)),
	DEFINE_MNODE(yuvo_r4_larb17_4,
		MASTER_LARB_PORT(SMMU_L17_P4_YUVO_R4),                     8, false, 0x0, SLAVE_LARB(17)),
	DEFINE_MNODE(drzh1no_r1_larb17_5,
		MASTER_LARB_PORT(SMMU_L17_P5_DRZH1NO_R1),                  9, true,  0x0, SLAVE_LARB(17)),
	DEFINE_MNODE(stg_r3_larb17_6,
		MASTER_LARB_PORT(SMMU_L17_P6_STG_R3),                      5, true,  0x0, SLAVE_LARB(17)),
	/* LARB19 */
	DEFINE_MNODE(dvs_rd_larb19_4,
		MASTER_LARB_PORT(SMMU_L19_P4_DVS_RD),                      8, false, 0x0, SLAVE_LARB(19)),
	DEFINE_MNODE(dvs_wt_larb19_5,
		MASTER_LARB_PORT(SMMU_L19_P5_DVS_WT),                      9, true,  0x0, SLAVE_LARB(19)),
	DEFINE_MNODE(dvp_rd_larb19_6,
		MASTER_LARB_PORT(SMMU_L19_P6_DVP_RD),                      8, false, 0x0, SLAVE_LARB(19)),
	DEFINE_MNODE(dvp_wt_larb19_7,
		MASTER_LARB_PORT(SMMU_L19_P7_DVP_WT),                      9, true,  0x0, SLAVE_LARB(19)),
	DEFINE_MNODE(dvgf_rd_larb19_10,
		MASTER_LARB_PORT(SMMU_L19_P10_DVGF_RD),                    8, false, 0x0, SLAVE_LARB(19)),
	DEFINE_MNODE(dvgf_wt_larb19_11,
		MASTER_LARB_PORT(SMMU_L19_P11_DVGF_WT),                    9, true,  0x0, SLAVE_LARB(19)),
	DEFINE_MNODE(stg_wr_larb19_12,
		MASTER_LARB_PORT(SMMU_L19_P12_STG_WR),                     5, true,  0x0, SLAVE_LARB(19)),
	/* LARB20 */
	DEFINE_MNODE(ovl_rdma4_hdr_larb20_0,
		MASTER_LARB_PORT(SMMU_L20_P0_OVL_RDMA4_HDR),               8, false, 0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma9_hdr_larb20_1,
		MASTER_LARB_PORT(SMMU_L20_P1_OVL_RDMA9_HDR),               8, false, 0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma0_hdr_larb20_2,
		MASTER_LARB_PORT(SMMU_L20_P2_OVL_RDMA0_HDR),               8, false, 0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma4_larb20_3,
		MASTER_LARB_PORT(SMMU_L20_P3_OVL_RDMA4),                   8, false, 0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma9_larb20_4,
		MASTER_LARB_PORT(SMMU_L20_P4_OVL_RDMA9),                   8, false, 0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma0_0_larb20_5,
		MASTER_LARB_PORT(SMMU_L20_P5_OVL_RDMA0),                   8, false, 0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma4_hdr_stash_larb20_7,
		MASTER_LARB_PORT(SMMU_L20_P7_OVL_RDMA4_HDR_STASH),         5, true,  0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma9_hdr_stash_larb20_8,
		MASTER_LARB_PORT(SMMU_L20_P8_OVL_RDMA9_HDR_STASH),         5, true,  0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma0_hdr_stash_larb20_9,
		MASTER_LARB_PORT(SMMU_L20_P9_OVL_RDMA0_HDR_STASH),         5, true,  0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma4_stash_larb20_10,
		MASTER_LARB_PORT(SMMU_L20_P10_OVL_RDMA4_STASH),            5, true,  0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma9_stash_larb20_11,
		MASTER_LARB_PORT(SMMU_L20_P11_OVL_RDMA9_STASH),            5, true,  0x0, SLAVE_LARB(20)),
	DEFINE_MNODE(ovl_rdma0_stash_larb20_12,
		MASTER_LARB_PORT(SMMU_L20_P12_OVL_RDMA0_STASH),            5, true,  0x0, SLAVE_LARB(20)),
	/* LARB21 */
	DEFINE_MNODE(ovl_rdma5_hdr_larb21_0,
		MASTER_LARB_PORT(SMMU_L21_P0_OVL_RDMA5_HDR),               8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma8_hdr_larb21_1,
		MASTER_LARB_PORT(SMMU_L21_P1_OVL_RDMA8_HDR),               8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma1_hdr_larb21_2,
		MASTER_LARB_PORT(SMMU_L21_P2_OVL_RDMA1_HDR),               8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma5_larb21_3,
		MASTER_LARB_PORT(SMMU_L21_P3_OVL_RDMA5),                   8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma8_larb21_4,
		MASTER_LARB_PORT(SMMU_L21_P4_OVL_RDMA8),                   8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma1_larb21_5,
		MASTER_LARB_PORT(SMMU_L21_P5_OVL_RDMA1),                   8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(mdp_rdma0_larb21_7,
		MASTER_LARB_PORT(SMMU_L21_P7_MDP_RDMA0),                   8, false, 0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(disp_wdma0_larb21_8,
		MASTER_LARB_PORT(SMMU_L21_P8_DISP_WDMA0),                  9, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(disp_ufbc_wdma0_larb21_9,
		MASTER_LARB_PORT(SMMU_L21_P9_DISP_UFBC_WDMA0),             9, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma5_hdr_stash_larb21_10,
		MASTER_LARB_PORT(SMMU_L21_P10_OVL_RDMA5_HDR_STASH),        5, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma8_hdr_stash_larb21_11,
		MASTER_LARB_PORT(SMMU_L21_P11_OVL_RDMA8_HDR_STASH),        5, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma1_hdr_stash_larb21_12,
		MASTER_LARB_PORT(SMMU_L21_P12_OVL_RDMA1_HDR_STASH),        5, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma5_stash_larb21_13,
		MASTER_LARB_PORT(SMMU_L21_P13_OVL_RDMA5_STASH),            5, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma8_stash_larb21_14,
		MASTER_LARB_PORT(SMMU_L21_P14_OVL_RDMA8_STASH),            5, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(ovl_rdma1_stash_larb21_15,
		MASTER_LARB_PORT(SMMU_L21_P15_OVL_RDMA1_STASH),            5, true,  0x0, SLAVE_LARB(21)),
	DEFINE_MNODE(mdp_rdma0_stash_larb21_16,
		MASTER_LARB_PORT(SMMU_L21_P16_MDP_RDMA0_STASH),            5, true,  0x0, SLAVE_LARB(21)),
	/* LARB24 */
	DEFINE_MNODE(jpgenc_y_rdma_larb24_7,
		MASTER_LARB_PORT(SMMU_L24_P7_JPGENC_YRD),                  7, false, 0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgenc_c_rdma_larb24_8,
		MASTER_LARB_PORT(SMMU_L24_P8_JPGENC_CRD),                  7, false, 0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgenc_q_table_larb24_9,
		MASTER_LARB_PORT(SMMU_L24_P9_JPGENC_QT),                   7, false, 0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgenc_bsdma_larb24_16,
		MASTER_LARB_PORT(SMMU_L24_P16_JPGENC_BS),                  8, true,  0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgdec_wdma_0_larb24_17,
		MASTER_LARB_PORT(SMMU_L24_P17_JPGDEC_W),                   8, true,  0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgdec_bsdma_0_larb24_18,
		MASTER_LARB_PORT(SMMU_L24_P18_JPGDEC_BS),                  7, false, 0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgdec_wdma_1_larb24_27,
		MASTER_LARB_PORT(SMMU_L24_P27_JPGDEC_W_1),                 8, true,  0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgdec_bsdma_1_larb24_28,
		MASTER_LARB_PORT(SMMU_L24_P28_JPGDEC_BS_1),                7, false, 0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgdec_huff_offset_1_larb24_29,
		MASTER_LARB_PORT(SMMU_L24_P29_JPGDEC_HUF_1),               8, true,  0x0, SLAVE_LARB(24)),
	DEFINE_MNODE(jpgdec_huff_offset_0_larb24_30,
		MASTER_LARB_PORT(SMMU_L24_P30_JPGDEC_HUF),                 8, true,  0x0, SLAVE_LARB(24)),
	/* LARB25 */
	DEFINE_MNODE(cqi_m1_larb25_0,
		MASTER_LARB_PORT(SMMU_L25_P0_CQI_M1),                      8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(imgo_m1_larb25_1,
		MASTER_LARB_PORT(SMMU_L25_P1_IMGO_M1),                     9, true,  0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(cqi_m1_larb25_2,
		MASTER_LARB_PORT(SMMU_L25_P2_CQI_M1),                      8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(imgo_m1_larb25_3,
		MASTER_LARB_PORT(SMMU_L25_P3_IMGO_M1),                     9, true,  0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(smir0_larb25_4,
		MASTER_LARB_PORT(SMMU_L25_P4_SMIR0),                       8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(smir1_larb25_5,
		MASTER_LARB_PORT(SMMU_L25_P5_SMIR1),                       8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(smir2_larb25_6,
		MASTER_LARB_PORT(SMMU_L25_P6_SMIR2),                       8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(smir3_larb25_7,
		MASTER_LARB_PORT(SMMU_L25_P7_SMIR3),                       8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(smir4_larb25_8,
		MASTER_LARB_PORT(SMMU_L25_P8_SMIR4),                       8, false, 0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(smiw_larb25_9,
		MASTER_LARB_PORT(SMMU_L25_P9_SMIW),                        9, true,  0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(stg_wr_larb25_10,
		MASTER_LARB_PORT(SMMU_L25_P10_STG_WR),                     5, true,  0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(stg_m1_larb25_11,
		MASTER_LARB_PORT(SMMU_L25_P11_STG_M1),                     5, true,  0x0, SLAVE_LARB(25)),
	DEFINE_MNODE(stg_m1_larb25_12,
		MASTER_LARB_PORT(SMMU_L25_P12_STG_M1),                     5, true,  0x0, SLAVE_LARB(25)),
	/* LARB26 */
	DEFINE_MNODE(cqi_m1_larb26_0,
		MASTER_LARB_PORT(SMMU_L26_P0_CQI_M1),                      8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(imgo_m1_larb26_1,
		MASTER_LARB_PORT(SMMU_L26_P1_IMGO_M1),                     9, true,  0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(cqi_m1_larb26_2,
		MASTER_LARB_PORT(SMMU_L26_P2_CQI_M1),                      8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(imgo_m1_larb26_3,
		MASTER_LARB_PORT(SMMU_L26_P3_IMGO_M1),                     9, true,  0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(smir0_larb26_4,
		MASTER_LARB_PORT(SMMU_L26_P4_SMIR0),                       8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(smir1_larb26_5,
		MASTER_LARB_PORT(SMMU_L26_P5_SMIR1),                       8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(smir2_larb26_6,
		MASTER_LARB_PORT(SMMU_L26_P6_SMIR2),                       8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(smir3_larb26_7,
		MASTER_LARB_PORT(SMMU_L26_P7_SMIR3),                       8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(smir4_larb26_8,
		MASTER_LARB_PORT(SMMU_L26_P8_SMIR4),                       8, false, 0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(smiw_larb26_9,
		MASTER_LARB_PORT(SMMU_L26_P9_SMIW),                        9, true,  0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(stg_wr_larb26_10,
		MASTER_LARB_PORT(SMMU_L26_P10_STG_WR),                     5, true,  0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(stg_m1_larb26_11,
		MASTER_LARB_PORT(SMMU_L26_P11_STG_M1),                     5, true,  0x0, SLAVE_LARB(26)),
	DEFINE_MNODE(stg_m1_larb26_12,
		MASTER_LARB_PORT(SMMU_L26_P12_STG_M1),                     5, true,  0x0, SLAVE_LARB(26)),
	///* LARB27 */
	DEFINE_MNODE(ipui_i1_adlrd_larb27_0,
		MASTER_LARB_PORT(SMMU_L27_P0_IPUI_I1),                     8, false, 0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(rootcq_cqi_e1_rootcq_larb27_1,
		MASTER_LARB_PORT(SMMU_L27_P1_ROOTCQ_CQI_E1),               8, false, 0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(ipuo_o1_adlwr_larb27_2,
		MASTER_LARB_PORT(SMMU_L27_P2_IPUO_O1),                     9, true,  0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(cqi_u1_uisp_larb27_3,
		MASTER_LARB_PORT(SMMU_L27_P3_CQI_U1),                      8, false, 0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(stg_u1_uisp_larb27_4,
		MASTER_LARB_PORT(SMMU_L27_P4_STG_U1),                      5, true,  0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(camsv_a1_wdma_larb27_5,
		MASTER_LARB_PORT(SMMU_L27_P5_CAMSV_A1_WDMA),               9, true,  0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(camsv_b1_wdma_larb27_6,
		MASTER_LARB_PORT(SMMU_L27_P6_CAMSV_B1_WDMA),               9, true,  0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(imgo_u1_uisp_larb27_7,
		MASTER_LARB_PORT(SMMU_L27_P7_IMGO_U1),                     9, true,  0x0, SLAVE_LARB(27)),
	DEFINE_MNODE(yuvo_u1_uisp_larb27_8,
		MASTER_LARB_PORT(SMMU_L27_P8_YUVO_U1),                     9, true,  0x0, SLAVE_LARB(27)),
	/* LARB29 */
	DEFINE_MNODE(camsv_c_cqi_e1_larb29_0,
		MASTER_LARB_PORT(SMMU_L29_P0_CAMSV_C_CQI_E1),              8, false, 0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_d_cqi_e1_larb29_1,
		MASTER_LARB_PORT(SMMU_L29_P1_CAMSV_D_CQI_E1),              8, false, 0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_e_cqi_e1_larb29_2,
		MASTER_LARB_PORT(SMMU_L29_P2_CAMSV_E_CQI_E1),              8, false, 0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_f_cqi_e1_larb29_3,
		MASTER_LARB_PORT(SMMU_L29_P3_CAMSV_F_CQI_E1),              8, false, 0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_c_wdma_larb29_4,
		MASTER_LARB_PORT(SMMU_L29_P4_CAMSV_C_WDMA),                9, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_d_wdma_larb29_5,
		MASTER_LARB_PORT(SMMU_L29_P5_CAMSV_D_WDMA),                9, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_e_wdma_larb29_6,
		MASTER_LARB_PORT(SMMU_L29_P6_CAMSV_E_WDMA),                9, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_f_wdma_larb29_7,
		MASTER_LARB_PORT(SMMU_L29_P7_CAMSV_F_WDMA),                9, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_c_stg_larb29_10,
		MASTER_LARB_PORT(SMMU_L29_P10_CAMSV_C_STG),                1, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_d_stg_larb29_11,
		MASTER_LARB_PORT(SMMU_L29_P11_CAMSV_D_STG),                1, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_e_stg_larb29_12,
		MASTER_LARB_PORT(SMMU_L29_P12_CAMSV_E_STG),                1, true,  0x0, SLAVE_LARB(29)),
	DEFINE_MNODE(camsv_f_stg_larb29_13,
		MASTER_LARB_PORT(SMMU_L29_P13_CAMSV_F_STG),                1, true,  0x0, SLAVE_LARB(29)),
	/* LARB30 */
	DEFINE_MNODE(ccui_0_larb30_0,
		MASTER_LARB_PORT(SMMU_L30_P0_CCUI),                        8, false, 0x0, SLAVE_LARB(30)),
	DEFINE_MNODE(ccuo_0_larb30_1,
		MASTER_LARB_PORT(SMMU_L30_P1_CCUO),                        9, true,  0x0, SLAVE_LARB(30)),
	DEFINE_MNODE(ccui_1_larb30_2,
		MASTER_LARB_PORT(SMMU_L30_P2_CCUI2),                       8, false, 0x0, SLAVE_LARB(30)),
	DEFINE_MNODE(ccuo_1_larb30_3,
		MASTER_LARB_PORT(SMMU_L30_P3_CCUO2),                       9, true,  0x0, SLAVE_LARB(30)),
	/* LARB32 */
	DEFINE_MNODE(disp_postmask0_larb32_4,
		MASTER_LARB_PORT(SMMU_L32_P4_DISP_POSTMASK0),              7, false, 0x0, SLAVE_LARB(32)),
	DEFINE_MNODE(disp_postmask1_larb32_5,
		MASTER_LARB_PORT(SMMU_L32_P5_DISP_POSTMASK1),              7, false, 0x0, SLAVE_LARB(32)),
	DEFINE_MNODE(disp_mdp_rdma0_larb32_6,
		MASTER_LARB_PORT(SMMU_L32_P6_DISP_MDP_RDMA0),              8, false, 0x0, SLAVE_LARB(32)),
	DEFINE_MNODE(disp_wdma0_larb32_7,
		MASTER_LARB_PORT(SMMU_L32_P7_DISP_WDMA0),                  9, true,  0x0, SLAVE_LARB(32)),
	DEFINE_MNODE(disp_mdp_rdma0_stash_larb32_9,
		MASTER_LARB_PORT(SMMU_L32_P9_DISP_MDP_RDMA0_STASH),        5, true,  0x0, SLAVE_LARB(32)),
	/* LARB33 */
	DEFINE_MNODE(disp1_oddmr0_dmrr0_larb33_0,
		MASTER_LARB_PORT(SMMU_L33_P0_DISP1_ODDMR0_DMRR0),          8, false, 0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_oddmr0_dbir_larb33_4,
		MASTER_LARB_PORT(SMMU_L33_P4_DISP1_ODDMR0_DBIR),           8, false, 0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_oddmr0_odr_larb33_5,
		MASTER_LARB_PORT(SMMU_L33_P5_DISP1_ODDMR0_ODR),            9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_oddmr0_odw_larb33_6,
		MASTER_LARB_PORT(SMMU_L33_P6_DISP1_ODDMR0_ODW),            9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_gdma_larb33_8,
		MASTER_LARB_PORT(SMMU_L33_P8_DISP1_GDMA0),                 9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_mdp_rdma1_larb33_9,
		MASTER_LARB_PORT(SMMU_L33_P9_DISP1_MDP_RDMA1),             9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_wdma1_larb33_10,
		MASTER_LARB_PORT(SMMU_L33_P10_DISP1_WDMA1),                9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_wdma2_larb33_11,
		MASTER_LARB_PORT(SMMU_L33_P11_DISP1_WDMA2),                9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_wdma3_larb33_12,
		MASTER_LARB_PORT(SMMU_L33_P12_DISP1_WDMA3),                9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_wdma4_larb33_13,
		MASTER_LARB_PORT(SMMU_L33_P13_DISP1_WDMA4),                9, true,  0x0, SLAVE_LARB(33)),
	DEFINE_MNODE(disp1_mdp_rdma1_stash_larb33_14,
		MASTER_LARB_PORT(SMMU_L33_P14_DISP1_MDP_RDMA1_STASH),      5, true,  0x0, SLAVE_LARB(33)),
	/* LARB34 */
	DEFINE_MNODE(ovl_rdma2_hdr_larb34_0,
		MASTER_LARB_PORT(SMMU_L34_P0_OVL_RDMA2_HDR),               7, false, 0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma7_hdr_larb34_1,
		MASTER_LARB_PORT(SMMU_L34_P1_OVL_RDMA7_HDR),               7, false, 0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma2_larb34_2,
		MASTER_LARB_PORT(SMMU_L34_P2_OVL_RDMA2),                   8, false, 0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma7_larb34_3,
		MASTER_LARB_PORT(SMMU_L34_P3_OVL_RDMA7),                   8, false, 0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma2_hdr_stash_larb34_6,
		MASTER_LARB_PORT(SMMU_L34_P6_OVL_RDMA2_HDR_STASH),         5, true,  0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma7_hdr_stash_larb34_7,
		MASTER_LARB_PORT(SMMU_L34_P7_OVL_RDMA7_HDR_STASH),         5, true,  0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma2_stash_larb34_8,
		MASTER_LARB_PORT(SMMU_L34_P8_OVL_RDMA2_STASH),             5, true,  0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(ovl_rdma7_stash_larb34_9,
		MASTER_LARB_PORT(SMMU_L34_P9_OVL_RDMA7_STASH),             5, true,  0x0, SLAVE_LARB(34)),
	DEFINE_MNODE(disp_fake0_larb34_12,
		MASTER_LARB_PORT(SMMU_L34_P12_DISP_FAKE0),                 8, false, 0x0, SLAVE_LARB(34)),
	/* LARB35 */
	DEFINE_MNODE(ovl_rdma3_hdr_larb35_0,
		MASTER_LARB_PORT(SMMU_L35_P0_OVL_RDMA3_HDR),               7, false, 0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma6_hdr_larb35_1,
		MASTER_LARB_PORT(SMMU_L35_P1_OVL_RDMA6_HDR),               7, false, 0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma3_larb35_2,
		MASTER_LARB_PORT(SMMU_L35_P2_OVL_RDMA3),                   8, false, 0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma6_larb35_3,
		MASTER_LARB_PORT(SMMU_L35_P3_OVL_RDMA6),                   8, false, 0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(mdp_rdma1_stash_larb35_4,
		MASTER_LARB_PORT(SMMU_L35_P4_MDP_RDMA1),                   8, false, 0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(disp_wdma1_larb35_6,
		MASTER_LARB_PORT(SMMU_L35_P6_DISP_WDMA1),                  9, true,  0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma3_hdr_stash_larb35_7,
		MASTER_LARB_PORT(SMMU_L35_P7_OVL_RDMA3_HDR_STASH),         5, true,  0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma6_hdr_stash_larb35_8,
		MASTER_LARB_PORT(SMMU_L35_P8_OVL_RDMA6_HDR_STASH),         5, true,  0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma3_stash_larb35_9,
		MASTER_LARB_PORT(SMMU_L35_P9_OVL_RDMA3_STASH),             5, true,  0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(ovl_rdma6_stash_larb35_10,
		MASTER_LARB_PORT(SMMU_L35_P10_OVL_RDMA6_STASH),            5, true,  0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(mdp_rdma1_stash_larb35_11,
		MASTER_LARB_PORT(SMMU_L35_P11_MDP_RDMA1_STASH),            5, true,  0x0, SLAVE_LARB(35)),
	DEFINE_MNODE(disp_fake1_larb35_15,
		MASTER_LARB_PORT(SMMU_L35_P15_DISP_FAKE1),                 8, false, 0x0, SLAVE_LARB(35)),
	/* LARB36 */
	DEFINE_MNODE(ovl_rdma4_hdr_larb36_0,
		MASTER_LARB_PORT(SMMU_L36_P0_OVL_RDMA4_HDR),               8, false, 0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma9_hdr_larb36_1,
		MASTER_LARB_PORT(SMMU_L36_P1_OVL_RDMA9_HDR),               8, false, 0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma0_hdr_larb36_2,
		MASTER_LARB_PORT(SMMU_L36_P2_OVL_RDMA0_HDR),               8, false, 0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma4_larb36_3,
		MASTER_LARB_PORT(SMMU_L36_P3_OVL_RDMA4),                   8, false, 0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma9_larb36_4,
		MASTER_LARB_PORT(SMMU_L36_P4_OVL_RDMA9),                   8, false, 0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma0_larb36_5,
		MASTER_LARB_PORT(SMMU_L36_P5_OVL_RDMA0),                   8, false, 0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma4_hdr_stash_larb36_7,
		MASTER_LARB_PORT(SMMU_L36_P7_OVL_RDMA4_HDR_STASH),         5, true,  0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma9_hdr_stash_larb36_8,
		MASTER_LARB_PORT(SMMU_L36_P8_OVL_RDMA9_HDR_STASH),         5, true,  0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma0_hdr_stash_larb36_9,
		MASTER_LARB_PORT(SMMU_L36_P9_OVL_RDMA0_HDR_STASH),         5, true,  0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma4_stash_larb36_10,
		MASTER_LARB_PORT(SMMU_L36_P10_OVL_RDMA4_STASH),            5, true,  0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma9_stash_larb36_11,
		MASTER_LARB_PORT(SMMU_L36_P11_OVL_RDMA9_STASH),            5, true,  0x0, SLAVE_LARB(36)),
	DEFINE_MNODE(ovl_rdma0_stash_larb36_12,
		MASTER_LARB_PORT(SMMU_L36_P12_OVL_RDMA0_STASH),            5, true,  0x0, SLAVE_LARB(36)),
	/* LARB37 */
	DEFINE_MNODE(ovl_rdma5_hdr_larb37_0,
		MASTER_LARB_PORT(SMMU_L37_P0_OVL_RDMA5_HDR),               8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma8_hdr_larb37_1,
		MASTER_LARB_PORT(SMMU_L37_P1_OVL_RDMA8_HDR),               8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma1_hdr_larb37_2,
		MASTER_LARB_PORT(SMMU_L37_P2_OVL_RDMA1_HDR),               8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma5_larb37_3,
		MASTER_LARB_PORT(SMMU_L37_P3_OVL_RDMA5),                   8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma8_larb37_4,
		MASTER_LARB_PORT(SMMU_L37_P4_OVL_RDMA8),                   8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma1_larb37_5,
		MASTER_LARB_PORT(SMMU_L37_P5_OVL_RDMA1),                   8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(mdp_rdma0_larb37_7,
		MASTER_LARB_PORT(SMMU_L37_P7_MDP_RDMA0),                   8, false, 0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(disp_wdma0_larb37_8,
		MASTER_LARB_PORT(SMMU_L37_P8_DISP_WDMA0),                  9, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(disp_ufbc_wdma0_larb37_9,
		MASTER_LARB_PORT(SMMU_L37_P9_DISP_UFBC_WDMA0),             9, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma5_hdr_stash_larb37_10,
		MASTER_LARB_PORT(SMMU_L37_P10_OVL_RDMA5_HDR_STASH),        5, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma8_hdr_stash_larb37_11,
		MASTER_LARB_PORT(SMMU_L37_P11_OVL_RDMA8_HDR_STASH),        5, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma1_hdr_stash_larb37_12,
		MASTER_LARB_PORT(SMMU_L37_P12_OVL_RDMA1_HDR_STASH),        5, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma5_stash_larb37_13,
		MASTER_LARB_PORT(SMMU_L37_P13_OVL_RDMA5_STASH),            5, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma8_stash_larb37_14,
		MASTER_LARB_PORT(SMMU_L37_P14_OVL_RDMA8_STASH),            5, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(ovl_rdma1_stash_larb37_15,
		MASTER_LARB_PORT(SMMU_L37_P15_OVL_RDMA1_STASH),            5, true,  0x0, SLAVE_LARB(37)),
	DEFINE_MNODE(mdp_rdma0_stash_larb37_16,
		MASTER_LARB_PORT(SMMU_L37_P16_MDP_RDMA0_STASH),            5, true,  0x0, SLAVE_LARB(37)),
	/* LARB41 */
	DEFINE_MNODE(jpgenc_stash_y_rdma_larb41_7,
		MASTER_LARB_PORT(SMMU_L41_P7_JPGENC_YRD),                  7, false, 0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgenc_stash_c_rdma_larb41_8,
		MASTER_LARB_PORT(SMMU_L41_P8_JPGENC_CRD),                  7, false, 0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgenc_stash_q_table_larb41_9,
		MASTER_LARB_PORT(SMMU_L41_P9_JPGENC_QT),                   7, false, 0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgenc_stash_bsdma_larb41_16,
		MASTER_LARB_PORT(SMMU_L41_P16_JPGENC_BS),                  8, true,  0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgdec_stash_wdma_0_larb41_17,
		MASTER_LARB_PORT(SMMU_L41_P17_JPGDEC_W),                   8, true,  0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgdec_stash_bsdma_0_larb41_18,
		MASTER_LARB_PORT(SMMU_L41_P18_JPGDEC_BS),                  7, false, 0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgdec_stash_wdma_1_larb41_27,
		MASTER_LARB_PORT(SMMU_L41_P27_JPGDEC_W_1),                 8, true,  0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgdec_stash_bsdma_1_larb41_28,
		MASTER_LARB_PORT(SMMU_L41_P28_JPGDEC_BS_1),                7, false, 0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgdec_stash_huff_offset_1_larb41_29,
		MASTER_LARB_PORT(SMMU_L41_P29_JPGDEC_HUF_1),               8, true,  0x0, SLAVE_LARB(41)),
	DEFINE_MNODE(jpgdec_stash_huff_offset_0_larb41_30,
		MASTER_LARB_PORT(SMMU_L41_P30_JPGDEC_HUF),                 8, true,  0x0, SLAVE_LARB(41)),
	/* LARB42 */
	DEFINE_MNODE(jpgenc_stash_y_rdma_larb42_7,
		MASTER_LARB_PORT(SMMU_L42_P7_JPGENC_YRD),                  7, false, 0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgenc_stash_c_rdma_larb42_8,
		MASTER_LARB_PORT(SMMU_L42_P8_JPGENC_CRD),                  7, false, 0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgenc_stash_q_table_larb42_9,
		MASTER_LARB_PORT(SMMU_L42_P9_JPGENC_QT),                   7, false, 0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgenc_stash_bsdma_larb42_16,
		MASTER_LARB_PORT(SMMU_L42_P16_JPGENC_BS),                  8, true,  0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgdec_stash_wdma_0_larb42_17,
		MASTER_LARB_PORT(SMMU_L42_P17_JPGDEC_W),                   8, true,  0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgdec_stash_bsdma_0_larb42_18,
		MASTER_LARB_PORT(SMMU_L42_P18_JPGDEC_BS),                  7, false, 0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgdec_stash_wdma_1_larb42_27,
		MASTER_LARB_PORT(SMMU_L42_P27_JPGDEC_W_1),                 5, true,  0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgdec_stash_bsdma_1_larb42_28,
		MASTER_LARB_PORT(SMMU_L42_P28_JPGDEC_BS_1),                7, false, 0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgdec_stash_huff_offset_1_larb42_29,
		MASTER_LARB_PORT(SMMU_L42_P29_JPGDEC_HUF_1),               8, true,  0x0, SLAVE_LARB(42)),
	DEFINE_MNODE(jpgdec_stash_huff_offset_0_larb42_30,
		MASTER_LARB_PORT(SMMU_L42_P30_JPGDEC_HUF),                 8, true,  0x0, SLAVE_LARB(42)),
	/* LARB43 */
	DEFINE_MNODE(cqi_r1_larb43_0,
		MASTER_LARB_PORT(SMMU_L43_P0_CQI_R1),                      8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(cqi_r5_larb43_1,
		MASTER_LARB_PORT(SMMU_L43_P1_CQI_R5),                      8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(rawi_r2_larb43_2,
		MASTER_LARB_PORT(SMMU_L43_P2_RAWI_R2),                     8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(rawi_r3_larb43_3,
		MASTER_LARB_PORT(SMMU_L43_P3_RAWI_R3),                     8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(rawi_r4_larb43_4,
		MASTER_LARB_PORT(SMMU_L43_P4_RAWI_R4),                     8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(rawi_r5_larb43_5,
		MASTER_LARB_PORT(SMMU_L43_P5_RAWI_R5),                     8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(bpci_r1_larb43_6,
		MASTER_LARB_PORT(SMMU_L43_P6_BPCI_R1),                     9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(bpci_r3_larb43_7,
		MASTER_LARB_PORT(SMMU_L43_P7_BPCI_R3),                     9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(grmgi_r1_larb43_8,
		MASTER_LARB_PORT(SMMU_L43_P8_GRMGI_R1),                    8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(lsci_r1_larb43_9,
		MASTER_LARB_PORT(SMMU_L43_P9_LSCI_R1),                     8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(imgo_r1_larb43_10,
		MASTER_LARB_PORT(SMMU_L43_P10_IMGO_R1),                    8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(imgo_r2_larb43_11,
		MASTER_LARB_PORT(SMMU_L43_P11_IMGO_R2),                    8, false, 0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(drzb2no_r1_larb43_12,
		MASTER_LARB_PORT(SMMU_L43_P12_DRZB2NO_R1),                 9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(drzb2nbo_r1_larb43_13,
		MASTER_LARB_PORT(SMMU_L43_P13_DRZB2NBO_R1),                9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(gmpo_r1_larb43_14,
		MASTER_LARB_PORT(SMMU_L43_P14_GMPO_R1),                    9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(drzb2nco_r1_larb43_15,
		MASTER_LARB_PORT(SMMU_L43_P15_DRZB2NCO_R1),                9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(awbo_r1_larb43_16,
		MASTER_LARB_PORT(SMMU_L43_P16_AWBO_R1),                    9, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(stg_r1_larb43_17,
		MASTER_LARB_PORT(SMMU_L43_P17_STG_R1),                     5, true,  0x0, SLAVE_LARB(43)),
	DEFINE_MNODE(stg_r2_larb43_18,
		MASTER_LARB_PORT(SMMU_L43_P18_STG_R2),                     5, true,  0x0, SLAVE_LARB(43)),
	/* LARB44 */
	DEFINE_MNODE(cqi_r1_larb44_0,
		MASTER_LARB_PORT(SMMU_L44_P0_CQI_R1),                      8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(cqi_r5_larb44_1,
		MASTER_LARB_PORT(SMMU_L44_P1_CQI_R5),                      8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(rawi_r2_larb44_2,
		MASTER_LARB_PORT(SMMU_L44_P2_RAWI_R2),                     8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(rawi_r3_larb44_3,
		MASTER_LARB_PORT(SMMU_L44_P3_RAWI_R3),                     8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(rawi_r4_larb44_4,
		MASTER_LARB_PORT(SMMU_L44_P4_RAWI_R4),                     8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(rawi_r5_larb44_5,
		MASTER_LARB_PORT(SMMU_L44_P5_RAWI_R5),                     8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(bpci_r1_larb44_6,
		MASTER_LARB_PORT(SMMU_L44_P6_BPCI_R1),                     9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(bpci_r3_larb44_7,
		MASTER_LARB_PORT(SMMU_L44_P7_BPCI_R3),                     9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(grmgi_r1_larb44_8,
		MASTER_LARB_PORT(SMMU_L44_P8_GRMGI_R1),                    8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(lsci_r1_larb44_9,
		MASTER_LARB_PORT(SMMU_L44_P9_LSCI_R1),                     8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(imgo_r1_larb44_10,
		MASTER_LARB_PORT(SMMU_L44_P10_IMGO_R1),                    8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(imgo_r2_larb44_11,
		MASTER_LARB_PORT(SMMU_L44_P11_IMGO_R2),                    8, false, 0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(drzb2no_r1_larb44_12,
		MASTER_LARB_PORT(SMMU_L44_P12_DRZB2NO_R1),                 9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(drzb2nbo_r1_larb44_13,
		MASTER_LARB_PORT(SMMU_L44_P13_DRZB2NBO_R1),                9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(gmpo_r1_larb44_14,
		MASTER_LARB_PORT(SMMU_L44_P14_GMPO_R1),                    9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(drzb2nco_r1_larb44_15,
		MASTER_LARB_PORT(SMMU_L44_P15_DRZB2NCO_R1),                9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(awbo_r1_larb44_16,
		MASTER_LARB_PORT(SMMU_L44_P16_AWBO_R1),                    9, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(stg_r1_larb44_17,
		MASTER_LARB_PORT(SMMU_L44_P17_STG_R1),                     5, true,  0x0, SLAVE_LARB(44)),
	DEFINE_MNODE(stg_r2_larb44_18,
		MASTER_LARB_PORT(SMMU_L44_P18_STG_R2),                     5, true,  0x0, SLAVE_LARB(44)),
	/* LARB45 */
	DEFINE_MNODE(yuvo_r1_larb45_0,
		MASTER_LARB_PORT(SMMU_L45_P0_YUVO_R1),                     9, true,  0x0, SLAVE_LARB(45)),
	DEFINE_MNODE(yuvo_r3_larb45_1,
		MASTER_LARB_PORT(SMMU_L45_P1_YUVO_R3),                     9, true,  0x0, SLAVE_LARB(45)),
	DEFINE_MNODE(yuvo_r2_larb45_2,
		MASTER_LARB_PORT(SMMU_L45_P2_YUVO_R2),                     9, true,  0x0, SLAVE_LARB(45)),
	DEFINE_MNODE(drzh2no_r1_larb45_3,
		MASTER_LARB_PORT(SMMU_L45_P3_DRZH2NO_R1),                  9, true,  0x0, SLAVE_LARB(45)),
	DEFINE_MNODE(yuvo_r4_larb45_4,
		MASTER_LARB_PORT(SMMU_L45_P4_YUVO_R4),                     8, false, 0x0, SLAVE_LARB(45)),
	DEFINE_MNODE(drzh1no_r1_larb45_5,
		MASTER_LARB_PORT(SMMU_L45_P5_DRZH1NO_R1),                  9, true,  0x0, SLAVE_LARB(45)),
	DEFINE_MNODE(stg_r3_larb45_6,
		MASTER_LARB_PORT(SMMU_L45_P6_STG_R3),                      5, true,  0x0, SLAVE_LARB(45)),
	/* LARB46 */
	DEFINE_MNODE(yuvo_r1_larb46_0,
		MASTER_LARB_PORT(SMMU_L46_P0_YUVO_R1),                     9, true,  0x0, SLAVE_LARB(46)),
	DEFINE_MNODE(yuvo_r3_larb46_1,
		MASTER_LARB_PORT(SMMU_L46_P1_YUVO_R3),                     9, true,  0x0, SLAVE_LARB(46)),
	DEFINE_MNODE(yuvo_r2_larb46_2,
		MASTER_LARB_PORT(SMMU_L46_P2_YUVO_R2),                     9, true,  0x0, SLAVE_LARB(46)),
	DEFINE_MNODE(drzh2no_r1_larb46_3,
		MASTER_LARB_PORT(SMMU_L46_P3_DRZH2NO_R1),                  9, true,  0x0, SLAVE_LARB(46)),
	DEFINE_MNODE(yuvo_r4_larb46_4,
		MASTER_LARB_PORT(SMMU_L46_P4_YUVO_R4),                     8, false, 0x0, SLAVE_LARB(46)),
	DEFINE_MNODE(drzh1no_r1_larb46_5,
		MASTER_LARB_PORT(SMMU_L46_P5_DRZH1NO_R1),                  9, true,  0x0, SLAVE_LARB(46)),
	DEFINE_MNODE(stg_r3_larb46_6,
		MASTER_LARB_PORT(SMMU_L46_P6_STG_R3),                      5, true,  0x0, SLAVE_LARB(46)),
	/* LARB47 */
	DEFINE_MNODE(jpgenc_stash_y_rdma_larb47_7,
		MASTER_LARB_PORT(SMMU_L47_P7_JPGENC_YRD),                  7, false, 0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgenc_stash_c_rdma_larb47_8,
		MASTER_LARB_PORT(SMMU_L47_P8_JPGENC_CRD),                  7, false, 0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgenc_stash_q_table_larb47_9,
		MASTER_LARB_PORT(SMMU_L47_P9_JPGENC_QT),                   7, false, 0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgenc_stash_bsdma_larb47_16,
		MASTER_LARB_PORT(SMMU_L47_P16_JPGENC_BS),                  8, true,  0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgdec_stash_wdma_0_larb47_17,
		MASTER_LARB_PORT(SMMU_L47_P17_JPGDEC_W),                   8, true,  0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgdec_stash_bsdma_0_larb47_18,
		MASTER_LARB_PORT(SMMU_L47_P18_JPGDEC_BS),                  7, false, 0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgdec_stash_wdma_1_larb47_27,
		MASTER_LARB_PORT(SMMU_L47_P27_JPGDEC_W_1),                 8, true,  0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgdec_stash_bsdma_1_larb47_28,
		MASTER_LARB_PORT(SMMU_L47_P28_JPGDEC_BS_1),                7, false, 0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgdec_stash_huff_offset_1_larb47_29,
		MASTER_LARB_PORT(SMMU_L47_P29_JPGDEC_HUF_1),               8, true,  0x0, SLAVE_LARB(47)),
	DEFINE_MNODE(jpgdec_stash_huff_offset_0_larb47_30,
		MASTER_LARB_PORT(SMMU_L47_P30_JPGDEC_HUF),                 8, true,  0x0, SLAVE_LARB(47)),
	/* LARB48 for MML IR & DL*/
	DEFINE_MNODE(mdp_rdma2_larb48_0,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 0)),                 8, false, 0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_wrot2_larb48_1,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 1)),                 7, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rdma1_larb48_2,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 2)),                 8, false, 0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_wrot1_larb48_3,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 3)),                 7, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rdma0_larb48_4,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 4)),                 8, false, 0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_wrot0_larb48_5,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 5)),                 7, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rrot0_larb48_6,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 6)),                 6, false, 0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_fg0_larb48_7,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 7)),                 7, false, 0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rdma2_stash_larb48_9,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 9)),                 5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_wrot2_stash_larb48_10,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 10)),                5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rdma1_stash_larb48_11,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 11)),                5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_wrot1_stash_larb48_12,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 12)),                5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rdma0_stash_larb48_13,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 13)),                5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_wrot0_stash_larb48_14,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 14)),                5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_rrot0_stash_larb48_15,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 15)),                5, true,  0x0, SLAVE_LARB(48)),
	DEFINE_MNODE(mdp_fake_eng0_larb48_17,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(48, 17)),                8, false, 0x0, SLAVE_LARB(48)),
	/* LARB49 for MDP RROT DL*/
	DEFINE_MNODE(mdp_rdma2_larb49_0,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 0)),                 8, false, 0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_wrot2_larb49_1,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 1)),                 7, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rdma1_larb49_2,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 2)),                 8, false, 0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_wrot1_larb49_3,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 3)),                 7, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rdma0_larb49_4,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 4)),                 8, false, 0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_wrot0_larb49_5,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 5)),                 7, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rrot0_larb49_6,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 6)),                 6, false, 0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_fg0_larb49_7,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 7)),                 7, false, 0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_wrot2_stash_larb49_9,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 9)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rdma1_stash_larb49_10,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 10)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_wrot1_stash_larb49_11,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 11)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rdma0_stash_larb49_12,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 12)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_wrot0_stash_larb49_13,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 13)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rrot0_stash_larb49_14,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 14)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_rdma2_stash_larb49_15,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 15)),		   5, true,  0x0, SLAVE_LARB(49)),
	DEFINE_MNODE(mdp_fake_eng0_larb49_17,
		MASTER_LARB_PORT(MTK_SMMU_PORT_ID(49, 17)),                8, false, 0x0, SLAVE_LARB(49)),
};
static const char * const comm_muxes_mt6991[] = { "mm", "mdp" };
static const char * const comm_icc_path_names_mt6991[] = { "icc-bw", "icc-bw" };
static const char * const comm_icc_hrt_path_names_mt6991[] = { "icc-hrt-bw", "icc-hrt-bw" };
static const struct mtk_mmqos_desc mmqos_desc_mt6991 = {
	.nodes = node_descs_mt6991,
	.num_nodes = ARRAY_SIZE(node_descs_mt6991),
	.comm_muxes = comm_muxes_mt6991,
	.comm_icc_path_names = comm_icc_path_names_mt6991,
	.comm_icc_hrt_path_names = comm_icc_hrt_path_names_mt6991,
	.max_ratio = 64,
	.hrt = {
		.hrt_bw = {12808, 0, 0},
		.hrt_total_bw = 68264, /* Todo: Use DRAMC API 8533*4(channel)*2(io width)*/
		.md_speech_bw = { 12808, 12183},
		.hrt_ratio = {1000, 850, 850, 850}, /* MD, CAM, DISP, MML */
		.blocking = true,
		.emi_ratio = 630,
	},
	.comm_port_hrt_types = {
		{ HRT_MAX_BWL, HRT_MAX_BWL, HRT_NONE, SRT_VENC, HRT_NONE,
			HRT_CAM, HRT_NONE, SRT_MDP, HRT_DISP },
		{ HRT_MAX_BWL, HRT_MAX_BWL, HRT_NONE, HRT_NONE, SRT_VENC,
			HRT_NONE, HRT_CAM, HRT_CAM, SRT_MML },
	},
	.report_bw_larbs = {SLAVE_LARB(49),	SLAVE_LARB(48),},
	.report_bw_real_larbs = {SLAVE_LARB(2),	SLAVE_LARB(3),},
	.disp_virt_larbs = { },
	.freq_mode = BY_VMMRC,
};
static const struct of_device_id mtk_mmqos_mt6991_of_ids[] = {
	{
		.compatible = "mediatek,mt6991-mmqos",
		.data = &mmqos_desc_mt6991,
	},
	{}
};
MODULE_DEVICE_TABLE(of, mtk_mmqos_mt6991_of_ids);
static struct platform_driver mtk_mmqos_mt6991_driver = {
	.probe = mtk_mmqos_v2_probe,
	.remove = mtk_mmqos_remove,
	.driver = {
		.name = "mtk-mt6991-mmqos",
		.of_match_table = mtk_mmqos_mt6991_of_ids,
	},
};
module_platform_driver(mtk_mmqos_mt6991_driver);
MODULE_LICENSE("GPL");
