#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019 MediaTek Inc.
#

ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/arm_div/

obj-$(CONFIG_ARM) := mtk_32bit_common.o
mtk_32bit_common-$(CONFIG_ARM) := arm_div.o