ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/cpuidle/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/spm/

obj-$(CONFIG_MEDIATEK_CPUIDLE) += mtk_cpuidle.o
