# SPDX-License-Identifier: GPL-2.0

#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

imgsensor_isp6s_mon-objs += ../common/v1_1/camera_hw/regulator/regulator.o
imgsensor_isp6s_mon-objs += ../common/v1_1/camera_hw/gpio/gpio.o
imgsensor_isp6s_mon-objs += ../common/v1_1/camera_hw/mclk/mclk.o

imgsensor_isp6s_mon-objs += camera_hw_mt6833/imgsensor_cfg_table.o