/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#ifndef __MTK_DCM_INTERNAL_H__
#define __MTK_DCM_INTERNAL_H__

#include <mtk_dcm_common.h>
#include "mt6991_dcm_autogen.h"

/* #define DCM_DEFAULT_ALL_OFF */

/* Note: ENABLE_DCM_IN_LK is used in kernel if DCM is enabled in LK */
#define ENABLE_DCM_IN_LK
#ifdef ENABLE_DCM_IN_LK
#define INIT_DCM_TYPE_BY_K	0
#endif

/* Note: DCM_TYPE enums is used in DCM init & SMC calls */
enum {
	INFRA_DCM = 0,
	MCUSYS_DCM = 1,
	MCUSYS_ACP_DCM = 2,
	MCUSYS_ADB_DCM = 3,
	MCUSYS_APB_DCM = 4,
	MCUSYS_BUS_DCM = 5,
	MCUSYS_CBIP_DCM = 6,
	MCUSYS_CHI_MON_DCM = 7,
	MCUSYS_CORE_DCM = 8,
	MCUSYS_DSU_ACP_DCM = 9,
	MCUSYS_EBG_DCM = 10,
	MCUSYS_GIC_SPI_DCM = 11,
	MCUSYS_IO_DCM = 12,
	MCUSYS_L3C_DCM = 13,
	MCUSYS_STALL_DCM = 14,
	PERI_DCM = 15,
	VLP_DCM = 16,
};

enum {
	INFRA_DCM_TYPE = BIT(INFRA_DCM),
	MCUSYS_DCM_TYPE = BIT(MCUSYS_DCM),
	MCUSYS_ACP_DCM_TYPE = BIT(MCUSYS_ACP_DCM),
	MCUSYS_ADB_DCM_TYPE = BIT(MCUSYS_ADB_DCM),
	MCUSYS_APB_DCM_TYPE = BIT(MCUSYS_APB_DCM),
	MCUSYS_BUS_DCM_TYPE = BIT(MCUSYS_BUS_DCM),
	MCUSYS_CBIP_DCM_TYPE = BIT(MCUSYS_CBIP_DCM),
	MCUSYS_CHI_MON_DCM_TYPE = BIT(MCUSYS_CHI_MON_DCM),
	MCUSYS_CORE_DCM_TYPE = BIT(MCUSYS_CORE_DCM),
	MCUSYS_DSU_ACP_DCM_TYPE = BIT(MCUSYS_DSU_ACP_DCM),
	MCUSYS_EBG_DCM_TYPE = BIT(MCUSYS_EBG_DCM),
	MCUSYS_GIC_SPI_DCM_TYPE = BIT(MCUSYS_GIC_SPI_DCM),
	MCUSYS_IO_DCM_TYPE = BIT(MCUSYS_IO_DCM),
	MCUSYS_L3C_DCM_TYPE = BIT(MCUSYS_L3C_DCM),
	MCUSYS_STALL_DCM_TYPE = BIT(MCUSYS_STALL_DCM),
	PERI_DCM_TYPE = BIT(PERI_DCM),
	VLP_DCM_TYPE = BIT(VLP_DCM),
};

int mt_dcm_dts_map(void);
void dcm_array_register(void);

#endif /* #ifndef __MTK_DCM_INTERNAL_H__ */
