subdir-ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/
hyp-obj-y := pkvm_smmu_hyp.o smmu_mgmt.o mpool.o arm_smmuv3.o mm.o arch_mm.o hf_smmu.o malloc.o
include $(srctree)/arch/arm64/kvm/hyp/nvhe/Makefile.module
