# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_TEE_PERF_SUPPORT) += teeperf/
obj-$(CONFIG_TRUSTONIC_TEE_SUPPORT) += gud/
obj-$(CONFIG_MICROTRUST_TEE_SUPPORT) += teei/
obj-$(CONFIG_MTK_OPTEE_SUPPORT) += optee/
