# SPDX-License-Identifier: GPL-2.0
#
# Makefile for MMC/SD host controller drivers
#
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/char/rpmb/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/blocktag/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/ufs/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/mmc/host
ccflags-y += -I$(srctree)/drivers/ufs/
ccflags-y += -I$(srctree)/drivers/mmc/host/
ccflags-y += -I$(srctree)/include/ufs/

obj-$(CONFIG_DEVICE_MODULES_MMC_MTK)			+= mtk-sd.o
obj-$(CONFIG_DEVICE_MODULES_MMC_MTK_PRO)		+= mtk-mmc.o
obj-$(CONFIG_DEVICE_MODULES_MMC_DEBUG)			+= mtk-mmc-dbg.o
obj-$(CONFIG_DEVICE_MODULES_MMC_MTK_MMC_WP)		+= mtk-mmc-wp.o
obj-$(CONFIG_DEVICE_MODULES_MMC_CQHCI)			+= cqhci.o
cqhci-y					+= cqhci-core.o
cqhci-$(CONFIG_MMC_CRYPTO)		+= cqhci-crypto.o
obj-$(CONFIG_DEVICE_MODULES_MMC_MTK_SW_CQHCI)		+= mtk-mmc-swcqhci.o
mtk-mmc-swcqhci-y			+= mtk-mmc-swcqhci-core.o
mtk-mmc-swcqhci-$(CONFIG_MMC_CRYPTO)	+= mtk-mmc-swcqhci-crypto.o
