ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
obj-m += botai_touch_one.o
botai_touch_one-y	+=  gt9xx_driver.o
botai_touch_one-y	+=  tpd_control.o
botai_touch_one-y	+=  tpd_button.o
