ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/accelerometer/inc
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/hwmon/include
#ccflags-y += -w

obj-$(CONFIG_MTK_SENSOR_SUPPORT)	+=  mc3410-i2c.o
