#
# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/thermal/v7/inc/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/base/power/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/gpu/hal/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/gpu/mediatek/mt-plat/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/gpu/mediatek/gpufreq/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/thermal/fakeHeader/

ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mcupm/include/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sspm/v2/

ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/spm/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/base/power/eem_v2/inc
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/pmic/include/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/thermal/common/inc/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y  += -I$(DEVICE_MODULES_PATH)/include/dt-bindings/